version: '3'

services:
  app:
    image: 'tmvdl/projects:antify'
    container_name: 'app'
    build: './src/app'
    ports:
      - '80:80'
    volumes:
      - './src/app:/app'
      - '/data:/data'
