version: '3'

services:

  app:
    image: 'tmvdl/projects:antify'
    build: './src/app'
    environment:
      - 'PORT=80'
      - 'PATH=/data'
    ports:
      - '8080:80'
    volumes:
      - './src/app:/app'
      - '/data:/data'

  github-release:
    image: 'github-release'
    build: './src/app'
