version: '3'

services:

  api:
    image: 'tmvdl/projects:antify'
    build: './src/api'
    environment:
      - 'ANTIFY_PORT=80'
      - 'ANTIFY_PATH=/data'
    ports:
      - '8080:80'
    volumes:
      - './src/api:/usr/local/go/src/github.com/brtmvdl/antify'
      - './data:/data'

  github-release:
    image: 'github-release'
    build: './src/api'
