name: antify 
base: core20 
version: '0.1.0' 
summary: A fast open source database
description: A fast open source database

grade: beta
confinement: strict

apps:
  antify:
    command: antify

parts:
  antify:
    plugin: go
    source: https://github.com/brtmvdl/antify.git
