name: antify 
base: core20 
version: '0.1' 
summary: A fast open source database
description: A fast open source database

grade: devel
confinement: devmode

apps:
  antify:
    command: antify
    daemon: simple
    plugs:
      - network
      - home

parts:
  antify:
    plugin: go
    source: https://github.com/brtmvdl/antify.git
    source-type: git
