name: antify 
base: core20 
version: '0.1' 
summary: A fast open source database
description: A fast open source database

grade: devel
confinement: devmode

architectures:
  - build-on: armhf
  - build-on: amd64
  - build-on: i386

apps:
  antify:
    command: antify
    daemon: simple
    plugs:
      - network
      - home

parts:
  antify:
    plugin: go
    source: ./src/app

