name: GitHub release

on:
  schedule:
    - cron: '50 23 * * *'
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Docker build
        run: docker-compose build github-release

      - name: Export app
        run: docker run -v $(pwd)/dist:/dist github-release /bin/cp -rfv /usr/local/go/src/github.com/brtmvdl/antify/antify /dist

      - name: Create release
        run: gh release create v$( date +%Y%m%d%H%M ) $(pwd)/dist/antify
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
