name: GitHub pages

on:
  schedule:
    - cron: '50 23 * * *'
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this project
        uses: actions/checkout@v3

      - name: Check out GitHub.io
        run: gh repo clone git@github.com:brtmvdl/brtmvdl.github.io.git ~/github
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy project
        run: cp -rfv src/github.io ~/github/projects

      - name: Sync repo
        run: gh repo sync
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
