name: Snapcraft Beta

on:
  schedule:
    - cron: '50 23 * * *'
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Snapcore build
      uses: snapcore/action-build@v1
      id: build-snap
      with:
        snapcraft-args: '--enable-experimental-extensions'

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Snapcore publish
      uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{ needs.build.outputs.snap-file }}
        release: beta

