name: Snapcraft Beta

on:
  schedule:
    - cron: '50 23 * * *'
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Snapcore action
      uses: snapcore/action-build@v1
      id: build-snap
      with:
        snapcraft-args: '--enable-experimental-extensions'

    - name: Snap install
      run: sudo snap install --dangerous ${{ steps.build-snap.outputs.snap }}

    - name:
      run: gbeuzeboc-snapped-ros2-pkg.snapped-ros2-launch --print-description

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: gbeuzeboc-snapped-ros2-pkg
        path: ${{ steps.build-snap.outputs.snap }}

  publish:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: gbeuzeboc-snapped-ros2-pkg
        path: .

    - name: Snapcore action
      uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
      with:
        snap: ${{needs.build.outputs.snap-file}}
        release: ${{ startsWith(github.ref, 'refs/tags/') && 'candidate' || 'edge'}}
