name: Snapcraft Beta

on:
  schedule:
    - cron: '50 23 * * *'
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  snapcraft:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Snap Install
      run: sudo apt update -y && sudo apt install -y snapd && sudo snap install snapcraft --classic 
      id: snapcraft

    - name: Snap Build
      run: echo Snap Build with $SNAPCRAFT_STORE_CREDENTIALS
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_CREDENTIALS }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}
