name: Snapcraft Beta

on:
  schedule:
    - cron: '50 23 * * *'
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  snapcraft:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Snap Install
      run: echo Instal Snap
      id: snapcraft

    - name: Snap Build
      run: echo Snap Build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}
